fix calling Disassembler constructor
fixes

```
dsm = Disassembler
insn = dsm.disassemble(tr)
insn.capstone_instruction

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_7414/3279911869.py in <module>
      1 dsm = Disassembler
----> 2 insn = dsm.disassemble(tr)
      3 # Access the capstone instruction
      4 insn.capstone_instruction

TypeError: disassemble() missing 1 required positional argument: 'tr'
```